### ISSUE TITLE
Bad rendering on login page

### ISSUE THREAD

**Issue by decisao** [creativetimofficial/ct-vue-now-ui-dashboard-pro#22]
Hello,

the login page is bad rendering after build:

https://gol.decisao.net/#/login

Can we fix that?

Thanks,
Eliéser

**Comment by cristijora** [comment]
Sorry for the late reply here. We usually respond to custom support done via website and fix github issues when they add up to 8-10 issues.

The link doesn't seem to work anymore.

**Comment by cristijora** [comment]
This issue should probably be fixed with the latest update which uses latest bootstrap version. Feel free to re-open the issue if the problem still persists.

To get the update, go to your accounts (Download section) and re-download the template, copy the `assets, components` and `vue.config.js` files. Also you could diff `package.json` to check what packages were upgraded.
